<a href="https://colab.research.google.com/github/kilkuwu/pytorch-deep-learning/blob/main/lessons/00/exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab"/></a>

# 00. Bài tập Kiến thức cơ bản PyTorch

### 1. Đọc tài liệu

Một phần lớn của deep learning (và học lập trình nói chung) là làm quen với tài liệu của framework cụ thể mà bạn đang sử dụng. Chúng ta sẽ sử dụng tài liệu PyTorch rất nhiều trong suốt phần còn lại của khóa học này. Vì vậy tôi khuyên bạn nên dành 10 phút đọc những điều sau (không sao nếu bạn không hiểu một số thứ ngay bây giờ, trọng tâm chưa phải là hiểu đầy đủ mà là nhận thức):
  * Tài liệu về [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * Tài liệu về [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).

In [ ]:
# Không có giải pháp code (đọc tài liệu)

### 2. Tạo một tensor ngẫu nhiên với shape `(7, 7)`.

In [ ]:
# Import torch

# Tạo tensor ngẫu nhiên


### 3. Thực hiện phép nhân ma trận trên tensor từ bài 2 với một tensor ngẫu nhiên khác có shape `(1, 7)` (gợi ý: bạn có thể phải transpose tensor thứ hai).

In [ ]:
# Tạo tensor ngẫu nhiên khác

# Thực hiện phép nhân ma trận


### 4. Đặt random seed thành `0` và làm lại bài 2 & 3.

Kết quả đầu ra sẽ là:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Đặt manual seed

# Tạo hai tensor ngẫu nhiên

# Nhân ma trận các tensors


### 5. Nói về random seeds, chúng ta đã thấy cách đặt nó với `torch.manual_seed()` nhưng có tương đương GPU không? (gợi ý: bạn sẽ cần xem vào tài liệu cho `torch.cuda` cho câu này)
  * Nếu có, đặt GPU random seed thành `1234`.

In [ ]:
# Đặt random seed trên GPU


### 6. Tạo hai tensor ngẫu nhiên có shape `(2, 3)` và gửi cả hai lên GPU (bạn sẽ cần quyền truy cập vào GPU cho việc này). Đặt `torch.manual_seed(1234)` khi tạo tensors (điều này không cần phải là GPU random seed). Kết quả đầu ra sẽ là một cái gì đó như:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Đặt random seed

# Kiểm tra quyền truy cập vào GPU

# Tạo hai tensor ngẫu nhiên trên GPU


Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

### 7. Thực hiện phép nhân ma trận trên các tensors bạn đã tạo ở bài 6 (một lần nữa, bạn có thể phải điều chỉnh shapes của một trong các tensors).

Kết quả đầu ra sẽ trông như:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Thực hiện matmul trên tensor_A và tensor_B


(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Tìm giá trị maximum và minimum của kết quả đầu ra từ bài 7.

In [ ]:
# Tìm max

# Tìm min


(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Tìm các giá trị chỉ mục maximum và minimum của kết quả đầu ra từ bài 7.

In [ ]:
# Tìm arg max

# Tìm arg min


(tensor(0, device='cuda:0'), tensor(3, device='cuda:0'))

### 10. Tạo một tensor ngẫu nhiên với shape `(1, 1, 1, 10)` và sau đó tạo một tensor mới với tất cả các chiều `1` được loại bỏ để còn lại một tensor có shape `(10)`. Đặt seed thành `7` khi bạn tạo nó và in ra tensor đầu tiên và shape của nó cũng như tensor thứ hai và shape của nó.

Kết quả đầu ra sẽ trông như:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Đặt seed

# Tạo tensor ngẫu nhiên

# Loại bỏ các chiều đơn

# In ra tensors và shapes của chúng


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))