<a href="https://colab.research.google.com/github/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a> 

# 00. Kiến thức cơ bản về PyTorch

## PyTorch là gì?

[PyTorch](https://pytorch.org/) là một framework học máy và học sâu mã nguồn mở.

## PyTorch có thể được sử dụng để làm gì?

PyTorch cho phép bạn thao tác và xử lý dữ liệu cũng như viết các thuật toán học máy bằng mã Python.

## Ai sử dụng PyTorch?

Nhiều công ty công nghệ lớn nhất thế giới như [Meta (Facebook)](https://ai.facebook.com/blog/pytorch-builds-the-future-of-ai-and-machine-learning-at-facebook/), Tesla và Microsoft cũng như các công ty nghiên cứu trí tuệ nhân tạo như [OpenAI sử dụng PyTorch](https://openai.com/blog/openai-pytorch/) để hỗ trợ nghiên cứu và đưa học máy vào các sản phẩm của họ.

![pytorch được sử dụng trong ngành và nghiên cứu](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-being-used-across-research-and-industry.png)

Ví dụ, Andrej Karpathy (trưởng phòng AI tại Tesla) đã có nhiều bài thuyết trình ([PyTorch DevCon 2019](https://youtu.be/oBklltKXtDE), [Tesla AI Day 2021](https://youtu.be/j0z4FweCy4M?t=2904)) về cách Tesla sử dụng PyTorch để vận hành các mô hình thị giác máy tính tự lái của họ.

PyTorch cũng được sử dụng trong các ngành khác như nông nghiệp để [hỗ trợ thị giác máy tính trên máy kéo](https://medium.com/pytorch/ai-for-ag-production-machine-learning-for-agriculture-e8cfdb9849a1).

## Tại sao nên sử dụng PyTorch?

Các nhà nghiên cứu học máy yêu thích sử dụng PyTorch. Và tính đến tháng 2 năm 2022, PyTorch là [framework học sâu được sử dụng nhiều nhất trên Papers With Code](https://paperswithcode.com/trends), một trang web để theo dõi các bài báo nghiên cứu học máy và các kho mã nguồn đi kèm.

PyTorch cũng giúp xử lý nhiều việc như tăng tốc GPU (làm cho mã của bạn chạy nhanh hơn) ở hậu trường.

Vì vậy bạn có thể tập trung vào thao tác dữ liệu và viết thuật toán còn PyTorch sẽ đảm bảo nó chạy nhanh.

Và nếu các công ty như Tesla và Meta (Facebook) sử dụng nó để xây dựng các mô hình họ triển khai để vận hành hàng trăm ứng dụng, lái hàng nghìn xe hơi và cung cấp nội dung cho hàng tỷ người, thì rõ ràng nó cũng có khả năng phát triển mạnh mẽ.

## Những gì chúng ta sẽ đề cập trong module này

Khóa học này được chia thành các phần khác nhau (notebooks).

Mỗi notebook bao gồm những ý tưởng và khái niệm quan trọng trong PyTorch.

Các notebook tiếp theo xây dựng dựa trên kiến thức từ notebook trước đó (đánh số bắt đầu từ 00, 01, 02 và tiếp tục cho đến số cuối cùng).

Notebook này đề cập đến khối xây dựng cơ bản của học máy và học sâu, đó là tensor.

Cụ thể, chúng ta sẽ đề cập:

| **Chủ đề** | **Nội dung** |
| ----- | ----- |
| **Giới thiệu về tensors** | Tensors là khối xây dựng cơ bản của tất cả học máy và học sâu. |
| **Tạo tensors** | Tensors có thể biểu diễn hầu hết mọi loại dữ liệu (hình ảnh, từ ngữ, bảng số). |
| **Lấy thông tin từ tensors** | Nếu bạn có thể đưa thông tin vào tensor, bạn cũng sẽ muốn lấy nó ra. |
| **Thao tác tensors** | Các thuật toán học máy (như mạng nơ-ron) bao gồm việc thao tác tensors theo nhiều cách khác nhau như cộng, nhân, kết hợp. | 
| **Xử lý hình dạng tensor** | Một trong những vấn đề phổ biến nhất trong học máy là xử lý sự không khớp hình dạng (cố gắng trộn tensors có hình dạng sai với tensors khác). |
| **Lập chỉ mục trên tensors** | Nếu bạn đã từng lập chỉ mục trên danh sách Python hoặc mảng NumPy, nó rất tương tự với tensors, ngoại trừ chúng có thể có nhiều chiều hơn rất nhiều. |
| **Kết hợp tensors PyTorch và NumPy** | PyTorch làm việc với tensors ([`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html)), NumPy thích arrays ([`np.ndarray`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)) đôi khi bạn sẽ muốn kết hợp và sử dụng cả hai. | 
| **Tính tái tạo** | Học máy rất thực nghiệm và vì nó sử dụng nhiều *tính ngẫu nhiên* để hoạt động, đôi khi bạn sẽ muốn *tính ngẫu nhiên* đó không quá ngẫu nhiên. |
| **Chạy tensors trên GPU** | GPUs (Graphics Processing Units) làm cho mã của bạn nhanh hơn, PyTorch giúp bạn dễ dàng chạy mã trên GPUs. |

## Bạn có thể tìm trợ giúp ở đâu?

Tất cả tài liệu cho khóa học này [có trên GitHub](https://github.com/mrdbourke/pytorch-deep-learning).

Và nếu bạn gặp khó khăn, bạn có thể đặt câu hỏi trên [trang Discussions](https://github.com/mrdbourke/pytorch-deep-learning/discussions) ở đó.

Ngoài ra còn có [diễn đàn nhà phát triển PyTorch](https://discuss.pytorch.org/), một nơi rất hữu ích cho mọi thứ liên quan đến PyTorch.

## Import PyTorch

> **Lưu ý:** Trước khi chạy bất kỳ mã nào trong notebook này, bạn nên đã thực hiện [các bước cài đặt PyTorch](https://pytorch.org/get-started/locally/). 
>
> Tuy nhiên, **nếu bạn đang chạy trên Google Colab**, mọi thứ sẽ hoạt động (Google Colab đi kèm với PyTorch và các thư viện khác đã được cài đặt).

Hãy bắt đầu bằng cách import PyTorch và kiểm tra phiên bản chúng ta đang sử dụng.

In [1]:
import torch
torch.__version__

'1.13.1+cu116'

Tuyệt vời, có vẻ như chúng ta đã có PyTorch 1.10.0+. 

Điều này có nghĩa nếu bạn đang theo dõi các tài liệu này, bạn sẽ thấy sự tương thích tốt nhất với PyTorch 1.10.0+, tuy nhiên nếu số phiên bản của bạn cao hơn nhiều so với đó, bạn có thể nhận thấy một số sự không nhất quán. 

Và nếu bạn gặp bất kỳ vấn đề nào, vui lòng đăng trên [trang GitHub Discussions của khóa học](https://github.com/mrdbourke/pytorch-deep-learning/discussions).

## Giới thiệu về tensors 

Bây giờ chúng ta đã import PyTorch, đã đến lúc tìm hiểu về tensors.

Tensors là khối xây dựng cơ bản của học máy.

Công việc của chúng là biểu diễn dữ liệu theo cách số học.

Ví dụ, bạn có thể biểu diễn một hình ảnh như một tensor với shape `[3, 224, 224]` có nghĩa là `[colour_channels, height, width]`, tức là hình ảnh có `3` kênh màu (đỏ, xanh lá, xanh dương), chiều cao `224` pixel và chiều rộng `224` pixel.

![ví dụ về việc chuyển từ hình ảnh đầu vào thành biểu diễn tensor của hình ảnh, hình ảnh được chia thành 3 kênh màu cũng như các số để biểu diễn chiều cao và chiều rộng](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-tensor-shape-example-of-image.png)

Trong ngôn ngữ tensor (ngôn ngữ được sử dụng để mô tả tensors), tensor sẽ có ba chiều, một cho `colour_channels`, `height` và `width`.

Nhưng chúng ta đang vượt quá xa.

Hãy tìm hiểu thêm về tensors bằng cách lập trình chúng.

### Tạo tensors 

PyTorch yêu thích tensors. Yêu thích đến mức có cả một trang tài liệu dành riêng cho lớp [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html).

Bài tập đầu tiên của bạn là [đọc qua tài liệu về `torch.Tensor`](https://pytorch.org/docs/stable/tensors.html) trong 10 phút. Nhưng bạn có thể để dành việc đó cho sau.

Hãy bắt đầu lập trình.

Điều đầu tiên chúng ta sẽ tạo là một **scalar**.

Scalar là một số đơn và trong ngôn ngữ tensor nó là một tensor không chiều.

> **Lưu ý:** Đó là một xu hướng cho khóa học này. Chúng ta sẽ tập trung vào viết mã cụ thể. Nhưng thường tôi sẽ đặt ra các bài tập liên quan đến việc đọc và làm quen với tài liệu PyTorch. Bởi vì suy cho cùng, một khi bạn hoàn thành khóa học này, chắc chắn bạn sẽ muốn học thêm. Và tài liệu là nơi bạn sẽ thường xuyên ghé thăm.

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

Thấy cách phía trên in ra `tensor(7)` không?

Điều đó có nghĩa là mặc dù `scalar` là một số đơn, nó có kiểu `torch.Tensor`.

Chúng ta có thể kiểm tra số chiều của một tensor bằng cách sử dụng thuộc tính `ndim`.

In [3]:
scalar.ndim

0

Nếu chúng ta muốn lấy số từ tensor thì sao?

Tức là, chuyển nó từ `torch.Tensor` thành một số nguyên Python?

Để làm điều đó chúng ta có thể sử dụng phương thức `item()`.

In [4]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

Được rồi, bây giờ hãy xem một **vector**.

Vector là một tensor một chiều nhưng có thể chứa nhiều số.

Tức là, bạn có thể có một vector `[3, 2]` để mô tả `[phòng ngủ, phòng tắm]` trong ngôi nhà của bạn. Hoặc bạn có thể có `[3, 2, 2]` để mô tả `[phòng ngủ, phòng tắm, chỗ đậu xe]` trong ngôi nhà của bạn.

Xu hướng quan trọng ở đây là vector linh hoạt trong việc nó có thể biểu diễn gì (tương tự với tensors).

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

Tuyệt vời, `vector` bây giờ chứa hai số 7, số yêu thích của tôi.

Bạn nghĩ nó sẽ có bao nhiêu chiều?

In [6]:
# Check the number of dimensions of vector
vector.ndim

1

Hmm, thật lạ, `vector` chứa hai số nhưng chỉ có một chiều duy nhất.

Tôi sẽ cho bạn biết một mẹo.

Bạn có thể biết số chiều của một tensor trong PyTorch bằng số dấu ngoặc vuông ở phía ngoài (`[`) và bạn chỉ cần đếm một bên.

`vector` có bao nhiêu dấu ngoặc vuông?

Một khái niệm quan trọng khác cho tensors là thuộc tính `shape` của chúng. Shape cho bạn biết các phần tử bên trong chúng được sắp xếp như thế nào.

Hãy kiểm tra shape của `vector`.

In [7]:
# Check shape of vector
vector.shape

torch.Size([2])

Phía trên trả về `torch.Size([2])` có nghĩa là vector của chúng ta có shape là `[2]`. Điều này là do hai phần tử chúng ta đặt bên trong dấu ngoặc vuông (`[7, 7]`).

Bây giờ hãy xem một **matrix**.

In [8]:
# Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

Wow! Nhiều số hơn! Matrices linh hoạt như vectors, ngoại trừ chúng có thêm một chiều.

In [9]:
# Check number of dimensions
MATRIX.ndim

2

`MATRIX` có hai chiều (bạn có đếm số dấu ngoặc vuông ở phía ngoài của một bên không?).

Bạn nghĩ nó sẽ có `shape` như thế nào?

In [10]:
MATRIX.shape

torch.Size([2, 2])

Chúng ta nhận được đầu ra `torch.Size([2, 2])` vì `MATRIX` có độ sâu hai phần tử và chiều rộng hai phần tử.

Còn việc tạo một **tensor** thì sao?

In [11]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

Woah! Một tensor đẹp quá!

Tôi muốn nhấn mạnh rằng tensors có thể biểu diễn hầu hết mọi thứ. 

Tensor chúng ta vừa tạo có thể là số liệu bán hàng cho một cửa hàng thịt bò và bơ hạnh nhân (hai trong số những thực phẩm yêu thích của tôi).

![một tensor đơn giản trong google sheets hiển thị ngày trong tuần, doanh số bán thịt bò và doanh số bán bơ hạnh nhân](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00_simple_tensor.png)

Bạn nghĩ nó có bao nhiêu chiều? (gợi ý: sử dụng mẹo đếm dấu ngoặc vuông)

In [12]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

Còn shape của nó thì sao?

In [13]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

Được rồi, nó xuất ra `torch.Size([1, 3, 3])`.

Các chiều đi từ ngoài vào trong.

Điều đó có nghĩa là có 1 chiều của 3 x 3.

![ví dụ về các chiều tensor khác nhau](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)

> **Lưu ý:** Bạn có thể nhận thấy tôi sử dụng chữ thường cho `scalar` và `vector` và chữ hoa cho `MATRIX` và `TENSOR`. Điều này là có chủ ý. Trong thực tế, bạn sẽ thường thấy scalars và vectors được ký hiệu bằng chữ thường như `y` hoặc `a`. Và matrices và tensors được ký hiệu bằng chữ hoa như `X` hoặc `W`.
>
> Bạn cũng có thể nhận thấy tên matrix và tensor được sử dụng thay thế cho nhau. Điều này phổ biến. Vì trong PyTorch bạn thường xuyên xử lý với `torch.Tensor`s (do đó có tên tensor), tuy nhiên, shape và chiều của những gì bên trong sẽ quyết định nó thực sự là gì.

Hãy tóm tắt.

| Tên | Nó là gì? | Số chiều | Chữ thường hay chữ hoa (thường/ví dụ) |
| ----- | ----- | ----- | ----- |
| **scalar** | một số đơn | 0 | Thường (`a`) | 
| **vector** | một số có hướng (ví dụ: tốc độ gió với hướng) nhưng cũng có thể có nhiều số khác | 1 | Thường (`y`) |
| **matrix** | một mảng 2 chiều các số | 2 | Hoa (`Q`) |
| **tensor** | một mảng n chiều các số | có thể là bất kỳ số nào, tensor 0 chiều là scalar, tensor 1 chiều là vector | Hoa (`X`) | 

![scalar vector matrix tensor và chúng trông như thế nào](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)

### Random tensors

Chúng ta đã thiết lập rằng tensors biểu diễn một số dạng dữ liệu.

Và các mô hình học máy như mạng nơ-ron thao tác và tìm kiếm các mẫu trong tensors.

Nhưng khi xây dựng các mô hình học máy với PyTorch, hiếm khi bạn tạo tensors bằng tay (như những gì chúng ta đang làm).

Thay vào đó, một mô hình học máy thường bắt đầu với các tensors ngẫu nhiên lớn các số và điều chỉnh những số ngẫu nhiên này khi nó làm việc qua dữ liệu để biểu diễn tốt hơn.

Về bản chất:

`Bắt đầu với số ngẫu nhiên -> xem dữ liệu -> cập nhật số ngẫu nhiên -> xem dữ liệu -> cập nhật số ngẫu nhiên...`

Với tư cách là một nhà khoa học dữ liệu, bạn có thể định nghĩa cách mô hình học máy bắt đầu (khởi tạo), xem dữ liệu (biểu diễn) và cập nhật (tối ưu hóa) các số ngẫu nhiên của nó.

Chúng ta sẽ thực hành với các bước này sau.

Bây giờ, hãy xem cách tạo một tensor các số ngẫu nhiên.

Chúng ta có thể làm điều đó bằng cách sử dụng [`torch.rand()`](https://pytorch.org/docs/stable/generated/torch.rand.html) và truyền vào tham số `size`.

In [14]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.6541, 0.4807, 0.2162, 0.6168],
         [0.4428, 0.6608, 0.6194, 0.8620],
         [0.2795, 0.6055, 0.4958, 0.5483]]),
 torch.float32)

Thật tuyệt! Chúng ta có một tensor với 3 hàng và 4 cột với các giá trị ngẫu nhiên.

Những số này đến từ đâu?

Chúng được lấy mẫu từ phân phối đồng nhất trong khoảng `[0, 1)`.

Và hình dạng của `random_tensor` là gì?

In [15]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Tuyệt vời!

Bạn cũng có thể tạo một tensor ngẫu nhiên với cùng hình dạng như một tensor khác.

In [16]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

### Tạo một tensor toàn số không hoặc toàn số một

Đôi khi bạn sẽ muốn điền một tensor với toàn số một hoặc toàn số không.

Bạn có thể làm điều đó với [`torch.zeros()`](https://pytorch.org/docs/stable/generated/torch.zeros.html) và [`torch.ones()`](https://pytorch.org/docs/stable/generated/torch.ones.html) tương ứng.

In [17]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Tạo một dãy tensors

Đôi khi bạn có thể muốn tạo một dãy số, chẳng hạn 1 đến 10 hoặc 0 đến 100.

Bạn có thể sử dụng [`torch.arange(start, end, step)`](https://pytorch.org/docs/stable/generated/torch.arange.html) để làm điều đó.

In [18]:
# Use torch.arange(), torch.range() is deprecated 
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

/tmp/ipykernel_3695928/193451495.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Bạn cũng có thể tạo tensors tương tự như các tensor khác.

In [19]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Kiểu dữ liệu tensor

Tensor datatype là một trong ba lỗi lớn bạn sẽ gặp phải với PyTorch & deep learning:
1. Tensors không có đúng `datatype`
2. Tensors không có đúng `shape` 
3. Tensors không ở trên đúng `device`

Chúng ta sẽ khám phá mỗi cái một.

Đầu tiên, datatype.

Datatype của tensor đề cập đến kiểu dữ liệu của dữ liệu được lưu trữ bên trong.

Ví dụ, nếu bạn tạo một tensor với `torch.float32`, tất cả dữ liệu bên trong đó sẽ có kiểu số thực dấu phẩy động 32-bit.

Và nếu bạn tạo một tensor với `torch.int64` (hoặc `torch.long`), dữ liệu bên trong sẽ có kiểu số nguyên dài.

Datatype nào bạn sử dụng sẽ phụ thuộc vào kiểu dữ liệu bạn đang lưu trữ và mức độ chính xác bạn muốn.

Higher precision = sử dụng nhiều bộ nhớ hơn, lower precision = sử dụng ít bộ nhớ hơn.

Nói chung, mặc định của PyTorch thường là `torch.float32` và `torch.long` là những lựa chọn tốt cho hầu hết các trường hợp sử dụng.

  * Xem [tài liệu PyTorch để biết danh sách tất cả các kiểu dữ liệu tensor có sẵn](https://pytorch.org/docs/stable/tensors.html#data-types).
  * Đọc [trang Wikipedia để có cái nhìn tổng quan về độ chính xác trong điện toán](https://en.wikipedia.org/wiki/Precision_(computer_science)) là gì.

Hãy xem cách tạo một số tensors với các kiểu dữ liệu cụ thể. Chúng ta có thể làm như vậy bằng cách sử dụng tham số `dtype`.

In [20]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

Ngoài các vấn đề về shape (hình dạng tensor không khớp), hai vấn đề phổ biến khác bạn sẽ gặp trong PyTorch là vấn đề về datatype và device.

Ví dụ, một trong các tensors là `torch.float32` và cái khác là `torch.float16` (PyTorch thường thích tensors có cùng định dạng).

Hoặc một trong các tensors của bạn ở trên CPU và cái khác ở trên GPU (PyTorch thích các phép tính giữa tensors ở trên cùng một device).

Chúng ta sẽ thấy thêm về chuyện device này sau.

Bây giờ hãy tạo một tensor với `dtype=torch.float16`.

In [21]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

## Lấy thông tin từ tensors

Một khi bạn đã tạo tensors (hoặc ai đó khác hoặc một module PyTorch đã tạo chúng cho bạn), bạn có thể muốn lấy một số thông tin từ chúng.

Chúng ta đã thấy những điều này trước đây nhưng ba trong số những thuộc tính phổ biến nhất bạn sẽ muốn tìm hiểu về tensors là:
* `shape` - tensor có hình dạng như thế nào? (một số phép toán yêu cầu các quy tắc shape cụ thể)
* `dtype` - các phần tử trong tensor được lưu trữ trong kiểu dữ liệu nào?
* `device` - tensor được lưu trữ trên device nào? (thường là GPU hoặc CPU)

Hãy tạo một tensor ngẫu nhiên và tìm hiểu chi tiết về nó.

In [22]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.4688, 0.0055, 0.8551, 0.0646],
        [0.6538, 0.5157, 0.4071, 0.2109],
        [0.9960, 0.3061, 0.9369, 0.7008]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


> **Lưu ý:** Khi bạn gặp vấn đề trong PyTorch, nó rất thường liên quan đến một trong ba thuộc tính ở trên. Vì vậy khi thông báo lỗi xuất hiện, hãy hát cho mình một bài hát nhỏ có tên "gì gì ở đâu": 
  * "*tensor của tôi có hình dạng gì? chúng có kiểu dữ liệu gì và chúng được lưu ở đâu? hình dạng gì, kiểu dữ liệu gì, ở đâu ở đâu ở đâu*"

## Thao tác tensors (các phép toán tensor)

Trong deep learning, dữ liệu (hình ảnh, văn bản, video, âm thanh, cấu trúc protein, v.v.) được biểu diễn dưới dạng tensors.

Một mô hình học bằng cách khám phá những tensors đó và thực hiện một loạt các phép toán (có thể là 1.000.000+ phép toán) trên tensors để tạo ra một biểu diễn của các mẫu trong dữ liệu đầu vào.

Những phép toán này thường là một điệu nhảy tuyệt vời giữa:
* Phép cộng
* Phép trừ
* Phép nhân (theo từng phần tử)
* Phép chia
* Phép nhân ma trận

Và đó là tất cả. Chắc chắn còn có một vài phép toán khác ở đây và ở đó nhưng đây là những khối xây dựng cơ bản của mạng nơ-ron.

Xếp chồng những khối xây dựng này theo cách đúng, bạn có thể tạo ra mạng nơ-ron tinh vi nhất (giống như lego!).

### Các phép toán cơ bản

Hãy bắt đầu với một vài phép toán cơ bản, phép cộng (`+`), phép trừ (`-`), phép nhân (`*`).

Chúng hoạt động đúng như bạn nghĩ.

In [23]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [24]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

Lưu ý cách các giá trị tensor ở trên không kết thúc bằng `tensor([110, 120, 130])`, điều này là do các giá trị bên trong tensor không thay đổi trừ khi chúng được gán lại.

In [25]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

Hãy trừ một số và lần này chúng ta sẽ gán lại biến `tensor`.

In [26]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [27]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

PyTorch cũng có một loạt các hàm tích hợp sẵn như [`torch.mul()`](https://pytorch.org/docs/stable/generated/torch.mul.html#torch.mul) (viết tắt của multiplication) và [`torch.add()`](https://pytorch.org/docs/stable/generated/torch.add.html) để thực hiện các phép toán cơ bản.

In [28]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [29]:
# Original tensor is still unchanged 
tensor

tensor([1, 2, 3])

Tuy nhiên, việc sử dụng các ký hiệu toán tử như `*` thay vì `torch.mul()` phổ biến hơn

In [30]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


### Phép nhân ma trận (là tất cả những gì bạn cần)

Một trong những phép toán phổ biến nhất trong các thuật toán học máy và deep learning (như mạng nơ-ron) là [phép nhân ma trận](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

PyTorch triển khai chức năng nhân ma trận trong phương thức [`torch.matmul()`](https://pytorch.org/docs/stable/generated/torch.matmul.html).

Hai quy tắc chính cho phép nhân ma trận cần nhớ là:

1. **Các chiều trong** phải khớp:
  * `(3, 2) @ (3, 2)` sẽ không hoạt động
  * `(2, 3) @ (3, 2)` sẽ hoạt động
  * `(3, 2) @ (2, 3)` sẽ hoạt động
2. Ma trận kết quả có hình dạng của **các chiều ngoài**:
 * `(2, 3) @ (3, 2)` -> `(2, 2)`
 * `(3, 2) @ (2, 3)` -> `(3, 3)`

> **Lưu ý:** "`@`" trong Python là ký hiệu cho phép nhân ma trận.

> **Tài nguyên:** Bạn có thể xem tất cả các quy tắc cho phép nhân ma trận sử dụng `torch.matmul()` [trong tài liệu PyTorch](https://pytorch.org/docs/stable/generated/torch.matmul.html).

Hãy tạo một tensor và thực hiện phép nhân theo từng phần tử và phép nhân ma trận trên nó.

In [31]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

Sự khác biệt giữa phép nhân theo từng phần tử và phép nhân ma trận là việc cộng các giá trị.

Đối với biến `tensor` của chúng ta với các giá trị `[1, 2, 3]`:

| Phép toán | Tính toán | Mã |
| ----- | ----- | ----- |
| **Phép nhân theo từng phần tử** | `[1*1, 2*2, 3*3]` = `[1, 4, 9]` | `tensor * tensor` |
| **Phép nhân ma trận** | `[1*1 + 2*2 + 3*3]` = `[14]` | `tensor.matmul(tensor)` |

In [32]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [33]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [34]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

Bạn có thể thực hiện phép nhân ma trận bằng tay nhưng không được khuyến nghị.

Phương thức `torch.matmul()` tích hợp sẵn nhanh hơn.

In [35]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 773 µs, sys: 0 ns, total: 773 µs
Wall time: 499 µs


tensor(14)

In [36]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 146 µs, sys: 83 µs, total: 229 µs
Wall time: 171 µs


tensor(14)

## Một trong những lỗi phổ biến nhất trong deep learning (lỗi shape)

Bởi vì phần lớn deep learning là nhân và thực hiện các phép toán trên ma trận và ma trận có quy tắc nghiêm ngặt về hình dạng và kích thước nào có thể được kết hợp, một trong những lỗi phổ biến nhất bạn sẽ gặp trong deep learning là sự không khớp về shape.

In [37]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

Chúng ta có thể làm cho phép nhân ma trận hoạt động giữa `tensor_A` và `tensor_B` bằng cách làm cho các chiều trong của chúng khớp.

Một trong những cách để làm điều này là với **transpose** (đổi chỗ các chiều của một tensor cho trước).

Bạn có thể thực hiện transpose trong PyTorch bằng cách sử dụng:
* `torch.transpose(input, dim0, dim1)` - trong đó `input` là tensor muốn transpose và `dim0` và `dim1` là các chiều sẽ được hoán đổi.
* `tensor.T` - trong đó `tensor` là tensor muốn transpose.

Hãy thử cách sau.

In [38]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [39]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [40]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


Bạn cũng có thể sử dụng [`torch.mm()`](https://pytorch.org/docs/stable/generated/torch.mm.html) là viết tắt của `torch.matmul()`.

In [41]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Không có transpose, các quy tắc của phép nhân ma trận không được thỏa mãn và chúng ta nhận được lỗi như ở trên.

Còn một hình ảnh trực quan thì sao? 

![demo trực quan của phép nhân ma trận](https://github.com/mrdbourke/pytorch-deep-learning/raw/main/images/00-matrix-multiply-crop.gif)

Bạn có thể tạo hình ảnh trực quan phép nhân ma trận của riêng mình như thế này tại http://matrixmultiplication.xyz/.

> **Lưu ý:** Một phép nhân ma trận như thế này cũng được gọi là [**dot product**](https://www.mathsisfun.com/algebra/vectors-dot-product.html) của hai ma trận.

Mạng nơ-ron chứa đầy các phép nhân ma trận và dot products.

Module [`torch.nn.Linear()`](https://pytorch.org/docs/1.9.1/generated/torch.nn.Linear.html) (chúng ta sẽ thấy điều này hoạt động sau), còn được gọi là feed-forward layer hoặc fully connected layer, triển khai một phép nhân ma trận giữa đầu vào `x` và ma trận trọng số `A`.

$$
y = x\cdot{A^T} + b
$$

Trong đó:
* `x` là đầu vào cho layer (deep learning là một chồng các layer như `torch.nn.Linear()` và các layer khác chồng lên nhau).
* `A` là ma trận trọng số được tạo bởi layer, điều này bắt đầu như các số ngẫu nhiên được điều chỉnh khi mạng nơ-ron học để biểu diễn tốt hơn các mẫu trong dữ liệu (lưu ý "`T`", đó là vì ma trận trọng số được transpose).
  * **Lưu ý:** Bạn cũng có thể thường thấy `W` hoặc chữ cái khác như `X` được sử dụng để thể hiện ma trận trọng số.
* `b` là bias term được sử dụng để bù đắp nhẹ cho trọng số và đầu vào.
* `y` là đầu ra (một thao tác của đầu vào với hy vọng khám phá các mẫu trong đó).

Đây là một hàm tuyến tính (bạn có thể đã thấy một cái gì đó như $y = mx+b$ ở trường trung học hoặc ở nơi khác), và có thể được sử dụng để vẽ một đường thẳng!

Hãy chơi với một linear layer.

Thử thay đổi các giá trị của `in_features` và `out_features` bên dưới và xem điều gì xảy ra.

Bạn có nhận thấy điều gì liên quan đến các hình dạng không?

In [42]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


## Tổng hợp, min, max, mean, sum (aggregation)

Thường khi làm việc với tensors, bạn có thể muốn làm một số tổng hợp các giá trị trong tensors (tìm giá trị tối thiểu, tối đa, trung bình, tổng, v.v.).

Tôi thích gọi chúng là các phép toán tập hợp/tổng hợp (aggregation operations).

Hãy tạo một tensor và thực hiện một số phép toán tổng hợp.

Để tìm min, max, mean, sum, v.v. của một tensor, bạn có thể sử dụng `torch.min(tensor)`, `torch.max(tensor)`, `torch.mean(tensor)` và `torch.sum(tensor)` tương ứng.

Hoặc bạn có thể sử dụng các phương thức tensor `tensor.min()`, `tensor.max()`, `tensor.mean()`, `tensor.sum()`.

Cơ bản thì cả hai đều làm cùng một việc.

Hoặc bạn có thể sử dụng phương thức tensor.

In [43]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

Bây giờ hãy thực hiện một số phép tổng hợp.

In [44]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


> **Lưu ý:** Bạn có thể thấy một số phương thức như `torch.mean()` yêu cầu tensors phải ở `torch.float32` (phổ biến nhất) hoặc kiểu dữ liệu cụ thể khác, nếu không phép toán sẽ thất bại. 

Bạn cũng có thể làm tương tự như trên với các phương thức `torch`.

In [45]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

### Vị trí min/max

Bạn cũng có thể tìm chỉ mục của tensor nơi giá trị max hoặc minimum xuất hiện với [`torch.argmax()`](https://pytorch.org/docs/stable/generated/torch.argmax.html) và [`torch.argmin()`](https://pytorch.org/docs/stable/generated/torch.argmin.html) tương ứng.

Điều này hữu ích trong trường hợp bạn chỉ muốn vị trí nơi giá trị cao nhất (hoặc thấp nhất) xuất hiện chứ không phải giá trị thực tế (chúng ta sẽ thấy điều này trong phần sau khi sử dụng [hàm kích hoạt softmax](https://pytorch.org/docs/stable/generated/torch.nn.Softmax.html)).

In [46]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


### Thay đổi kiểu dữ liệu tensor

Như đã đề cập, một vấn đề phổ biến với các phép toán deep learning là có tensors trong các kiểu dữ liệu khác nhau.

Nếu một tensor ở `torch.float64` và tensor khác ở `torch.float32`, bạn có thể gặp một số lỗi.

Nhưng có một cách khắc phục.

Bạn có thể thay đổi kiểu dữ liệu của tensors bằng [`torch.Tensor.type(dtype=None)`](https://pytorch.org/docs/stable/generated/torch.Tensor.type.html) trong đó tham số `dtype` là kiểu dữ liệu bạn muốn sử dụng.

Đầu tiên chúng ta sẽ tạo một tensor và kiểm tra kiểu dữ liệu của nó (mặc định là `torch.float32`).

In [47]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

Bây giờ chúng ta sẽ tạo một tensor khác giống như trước nhưng thay đổi kiểu dữ liệu thành `torch.float16`.

In [48]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

Và chúng ta có thể làm điều tương tự để tạo tensor `torch.int8`.

In [49]:
# Create an int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

> **Lưu ý:** Các kiểu dữ liệu khác nhau có thể gây nhầm lẫn ban đầu. Nhưng hãy nghĩ về nó như thế này, số càng thấp (ví dụ: 32, 16, 8), máy tính lưu trữ giá trị càng ít chính xác. Và với lượng lưu trữ thấp hơn, điều này thường dẫn đến tính toán nhanh hơn và mô hình tổng thể nhỏ hơn. Mạng nơ-ron dựa trên thiết bị di động thường hoạt động với số nguyên 8-bit, nhỏ hơn và chạy nhanh hơn nhưng ít chính xác hơn so với các đối tác float32 của chúng. Để biết thêm về điều này, tôi khuyên bạn nên đọc về [độ chính xác trong điện toán](https://en.wikipedia.org/wiki/Precision_(computer_science)).

> **Bài tập:** Cho đến nay chúng ta đã đề cập khá nhiều phương thức tensor nhưng còn rất nhiều phương thức khác trong [tài liệu `torch.Tensor`](https://pytorch.org/docs/stable/tensors.html), tôi khuyên bạn nên dành 10 phút cuộn qua và xem bất cứ phương thức nào thu hút mắt bạn. Nhấp vào chúng và sau đó tự viết ra bằng mã để xem điều gì xảy ra.

### Reshape, stack, squeeze và unsqueeze

Thường xuyên bạn sẽ muốn reshape hoặc thay đổi chiều của tensors mà không thực sự thay đổi các giá trị bên trong chúng.

Để làm như vậy, một số phương thức phổ biến là:

| Phương thức | Mô tả một dòng |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshape `input` thành `shape` (nếu tương thích), cũng có thể sử dụng `torch.Tensor.reshape()`. |
| [`Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Trả về một view của tensor gốc với `shape` khác nhưng chia sẻ cùng dữ liệu với tensor gốc. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Nối một chuỗi `tensors` theo một chiều mới (`dim`), tất cả `tensors` phải có cùng kích thước. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeeze `input` để loại bỏ tất cả các chiều có giá trị `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Trả về `input` với giá trị chiều `1` được thêm vào `dim`. | 
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Trả về một *view* của `input` gốc với các chiều được hoán vị (sắp xếp lại) thành `dims`. | 

Tại sao phải làm những điều này?

Bởi vì các mô hình deep learning (mạng nơ-ron) đều về việc thao tác tensors theo cách nào đó. Và do các quy tắc của phép nhân ma trận, nếu bạn có sự không khớp về shape, bạn sẽ gặp lỗi. Những phương thức này giúp bạn đảm bảo các phần tử đúng của tensors đang trộn với các phần tử đúng của tensors khác. 

Hãy thử chúng.

Đầu tiên, chúng ta sẽ tạo một tensor.

In [50]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

Bây giờ hãy thêm một chiều bổ sung với `torch.reshape()`.

In [51]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

Chúng ta cũng có thể thay đổi view với `torch.view()`.

In [52]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

Tuy nhiên hãy nhớ rằng, thay đổi view của tensor với `torch.view()` thực sự chỉ tạo một view mới của *cùng* tensor.

Vì vậy thay đổi view cũng thay đổi tensor gốc.

In [53]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

Nếu chúng ta muốn xếp chồng tensor mới lên trên chính nó năm lần, chúng ta có thể làm như vậy với `torch.stack()`.

In [54]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

Còn việc loại bỏ tất cả các chiều đơn từ tensor thì sao?

Để làm như vậy bạn có thể sử dụng `torch.squeeze()` (tôi nhớ điều này như việc *nén* tensor để chỉ có các chiều lớn hơn 1).

In [55]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


Và để làm ngược lại với `torch.squeeze()` bạn có thể sử dụng `torch.unsqueeze()` để thêm giá trị chiều 1 tại một chỉ mục cụ thể.

In [56]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


Bạn cũng có thể sắp xếp lại thứ tự các giá trị trục với `torch.permute(input, dims)`, trong đó `input` được chuyển thành một *view* với `dims` mới.

In [57]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


> **Lưu ý**: Bởi vì permuting trả về một *view* (chia sẻ cùng dữ liệu với tensor gốc), các giá trị trong tensor được permuted sẽ giống với tensor gốc và nếu bạn thay đổi các giá trị trong view, nó sẽ thay đổi các giá trị của tensor gốc.

## Lập chỉ mục (chọn dữ liệu từ tensors)

Đôi khi bạn sẽ muốn chọn dữ liệu cụ thể từ tensors (ví dụ: chỉ cột đầu tiên hoặc hàng thứ hai).

Để làm như vậy, bạn có thể sử dụng lập chỉ mục.

Nếu bạn đã từng lập chỉ mục trên danh sách Python hoặc mảng NumPy, lập chỉ mục trong PyTorch với tensors rất tương tự.

In [ ]:
Hãy tạo một tensor 3-chiều và index trên nó.

Lập chỉ mục các giá trị đi từ chiều ngoài -> chiều trong (hãy kiểm tra các dấu ngoặc vuông).

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

Lập chỉ mục các giá trị đi từ chiều ngoài -> chiều trong (hãy kiểm tra các dấu ngoặc vuông).

In [59]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


Bạn cũng có thể sử dụng `:` để chỉ định "tất cả giá trị trong chiều này" và sau đó sử dụng dấu phẩy (`,`) để thêm chiều khác.

In [60]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [61]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [62]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [63]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

Lập chỉ mục có thể khá gây nhầm lẫn ban đầu, đặc biệt với các tensors lớn hơn (tôi vẫn phải thử lập chỉ mục nhiều lần để làm đúng). Nhưng với một chút luyện tập và tuân theo phương châm của nhà thám hiểm dữ liệu (***trực quan hóa, trực quan hóa, trực quan hóa***), bạn sẽ bắt đầu nắm được.

## PyTorch tensors & NumPy

Vì NumPy là một thư viện tính toán số học Python phổ biến, PyTorch có chức năng tương tác với nó một cách tốt đẹp.  

Hai phương thức chính bạn sẽ muốn sử dụng để chuyển từ NumPy sang PyTorch (và ngược lại) là: 
* [`torch.from_numpy(ndarray)`](https://pytorch.org/docs/stable/generated/torch.from_numpy.html) - NumPy array -> PyTorch tensor. 
* [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) - PyTorch tensor -> NumPy array.

Hãy thử chúng.

In [64]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

> **Lưu ý:** Mặc định, các mảng NumPy được tạo với kiểu dữ liệu `float64` và nếu bạn chuyển đổi nó thành tensor PyTorch, nó sẽ giữ cùng kiểu dữ liệu (như trên). 
>
> Tuy nhiên, nhiều phép tính PyTorch mặc định sử dụng `float32`. 
> 
> Vì vậy nếu bạn muốn chuyển đổi mảng NumPy (float64) -> tensor PyTorch (float64) -> tensor PyTorch (float32), bạn có thể sử dụng `tensor = torch.from_numpy(array).type(torch.float32)`.

Bởi vì chúng ta đã gán lại `tensor` ở trên, nếu bạn thay đổi tensor, array vẫn giữ nguyên.

In [65]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Và nếu bạn muốn chuyển từ tensor PyTorch sang mảng NumPy, bạn có thể gọi `tensor.numpy()`.

In [66]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Và quy tắc tương tự áp dụng như trên, nếu bạn thay đổi `tensor` gốc, `numpy_tensor` mới vẫn giữ nguyên.

In [67]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Tính tái tạo (cố gắng loại bỏ tính ngẫu nhiên khỏi ngẫu nhiên)

Khi bạn tìm hiểu thêm về mạng nơ-ron và học máy, bạn sẽ bắt đầu khám phá ra tính ngẫu nhiên đóng vai trò quan trọng như thế nào.

Vâng, đó là tính giả ngẫu nhiên. Bởi vì suy cho cùng, theo cách chúng được thiết kế, máy tính về cơ bản là xác định (mỗi bước đều có thể dự đoán được) vì vậy tính ngẫu nhiên mà chúng tạo ra là tính ngẫu nhiên mô phỏng (mặc dù cũng có tranh luận về điều này, nhưng vì tôi không phải là nhà khoa học máy tính, tôi sẽ để bạn tự tìm hiểu thêm).

Điều này liên quan đến mạng nơ-ron và deep learning như thế nào?

Chúng ta đã thảo luận về việc mạng nơ-ron bắt đầu với các số ngẫu nhiên để mô tả các mẫu trong dữ liệu (những số này là mô tả kém) và cố gắng cải thiện những số ngẫu nhiên đó bằng cách sử dụng các phép toán tensor (và một vài thứ khác mà chúng ta chưa thảo luận) để mô tả tốt hơn các mẫu trong dữ liệu.

Tóm lại: 

``bắt đầu với số ngẫu nhiên -> phép toán tensor -> cố gắng làm tốt hơn (lặp đi lặp lại)``

Mặc dù tính ngẫu nhiên tốt và mạnh mẽ, đôi khi bạn muốn có ít tính ngẫu nhiên hơn.

Tại sao?

Để bạn có thể thực hiện các thí nghiệm lặp lại được.

Ví dụ, bạn tạo một thuật toán có thể đạt được hiệu suất X.

Và sau đó bạn bè của bạn thử nó để xác minh bạn không điên.

Họ có thể làm điều đó như thế nào?

Đó là lúc **tính tái tạo** xuất hiện.

Nói cách khác, bạn có thể có được kết quả giống nhau (hoặc rất tương tự) trên máy tính của bạn chạy cùng mã với những gì tôi có trên máy của tôi không?

Hãy xem một ví dụ ngắn về tính tái tạo trong PyTorch.

Chúng ta sẽ bắt đầu bằng cách tạo hai tensor ngẫu nhiên, vì chúng ngẫu nhiên, bạn mong đợi chúng khác nhau phải không?

In [68]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])

Tensor B:
tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Đúng như bạn có thể mong đợi, các tensors ra với các giá trị khác nhau.

Nhưng nếu bạn muốn tạo hai tensor ngẫu nhiên với các giá trị *giống nhau* thì sao.

Tức là, các tensors vẫn sẽ chứa các giá trị ngẫu nhiên nhưng chúng sẽ có cùng hương vị.

Đó là lúc [`torch.manual_seed(seed)`](https://pytorch.org/docs/stable/generated/torch.manual_seed.html) xuất hiện, trong đó `seed` là một số nguyên (như `42` nhưng có thể là bất cứ gì) tạo hương vị cho tính ngẫu nhiên.

Hãy thử bằng cách tạo một số tensor ngẫu nhiên *có hương vị*.

In [69]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

Tuyệt!

Có vẻ như việc thiết lập seed đã hoạt động. 

> **Tài nguyên:** Những gì chúng ta vừa đề cập chỉ chạm vào bề mặt của tính tái tạo trong PyTorch. Để biết thêm về tính tái tạo nói chung và random seeds, tôi khuyên bạn nên xem:
> * [Tài liệu tính tái tạo PyTorch](https://pytorch.org/docs/stable/notes/randomness.html) (một bài tập tốt sẽ là đọc qua điều này trong 10 phút và ngay cả khi bạn không hiểu nó bây giờ, việc nhận biết nó là quan trọng).
> * [Trang Wikipedia về random seed](https://en.wikipedia.org/wiki/Random_seed) (điều này sẽ cung cấp cái nhìn tổng quan tốt về random seeds và tính giả ngẫu nhiên nói chung).

## Chạy tensors trên GPUs (và tính toán nhanh hơn)

Các thuật toán deep learning yêu cầu rất nhiều phép toán số học.

Và mặc định những phép toán này thường được thực hiện trên CPU (computer processing unit).

Tuy nhiên, có một phần cứng phổ biến khác gọi là GPU (graphics processing unit), thường nhanh hơn nhiều trong việc thực hiện các loại phép toán cụ thể mà mạng nơ-ron cần (phép nhân ma trận) so với CPU.

Máy tính của bạn có thể có một cái.

Nếu có, bạn nên tìm cách sử dụng nó bất cứ khi nào có thể để huấn luyện mạng nơ-ron vì có khả năng nó sẽ tăng tốc thời gian huấn luyện đáng kể.

Có một vài cách để đầu tiên có quyền truy cập vào GPU và thứ hai là làm cho PyTorch sử dụng GPU.

> **Lưu ý:** Khi tôi tham chiếu "GPU" trong suốt khóa học này, tôi đang tham chiếu một [Nvidia GPU với CUDA](https://developer.nvidia.com/cuda-gpus) được bật (CUDA là một nền tảng tính toán và API giúp cho phép GPUs được sử dụng cho tính toán mục đích chung & không chỉ đồ họa) trừ khi được chỉ định khác.

### 1. Có GPU

Bạn có thể đã biết điều gì đang xảy ra khi tôi nói GPU. Nhưng nếu không, có một vài cách để có quyền truy cập vào một cái.

| **Phương pháp** | **Độ khó cài đặt** | **Ưu điểm** | **Nhược điểm** | **Cách cài đặt** |
| ----- | ----- | ----- | ----- | ----- |
| Google Colab | Dễ | Miễn phí sử dụng, gần như không cần cài đặt, có thể chia sẻ công việc với người khác dễ dàng như một link | Không lưu đầu ra dữ liệu của bạn, tính toán hạn chế, có thể bị timeout | [Theo dõi Hướng dẫn Google Colab](https://colab.research.google.com/notebooks/gpu.ipynb) |
| Sử dụng của riêng bạn | Trung bình | Chạy mọi thứ cục bộ trên máy của riêng bạn | GPUs không miễn phí, yêu cầu chi phí trả trước | Theo dõi [hướng dẫn cài đặt PyTorch](https://pytorch.org/get-started/locally/) |
| Cloud computing (AWS, GCP, Azure) | Trung bình-Khó | Chi phí trả trước nhỏ, truy cập vào tính toán gần như vô hạn | Có thể trở nên đắt đỏ nếu chạy liên tục, mất thời gian để cài đặt đúng | Theo dõi [hướng dẫn cài đặt PyTorch](https://pytorch.org/get-started/cloud-partners/) |

Có nhiều tùy chọn khác để sử dụng GPUs nhưng ba cái trên sẽ đủ cho bây giờ.

Cá nhân, tôi sử dụng kết hợp Google Colab và máy tính cá nhân của riêng tôi cho các thí nghiệm quy mô nhỏ (và tạo khóa học này) và chuyển sang tài nguyên cloud khi tôi cần nhiều sức mạnh tính toán hơn.

> **Tài nguyên:** Nếu bạn đang muốn mua GPU của riêng mình nhưng không chắc nên mua gì, [Tim Dettmers có một hướng dẫn xuất sắc](https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning/).

Để kiểm tra xem bạn có quyền truy cập vào Nvidia GPU không, bạn có thể chạy `!nvidia-smi` trong đó `!` (còn gọi là bang) có nghĩa là "chạy điều này trên command line".

In [70]:
!nvidia-smi

Sat Jan 21 08:34:23 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.48.07    Driver Version: 515.48.07    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA TITAN RTX    On   | 00000000:01:00.0 Off |                  N/A |
| 40%   30C    P8     7W / 280W |    177MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

Nếu bạn không có Nvidia GPU có thể truy cập, lệnh trên sẽ xuất ra một cái gì đó như:

```
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```

Trong trường hợp đó, hãy quay lại và làm theo các bước cài đặt.

Nếu bạn có GPU, dòng trên sẽ xuất ra một cái gì đó như:

```
Wed Jan 19 22:09:08 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.46       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P0    27W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

### 2. Làm cho PyTorch chạy trên GPU

Một khi bạn đã có GPU sẵn sàng để truy cập, bước tiếp theo là làm cho PyTorch sử dụng để lưu trữ dữ liệu (tensors) và tính toán trên dữ liệu (thực hiện các phép toán trên tensors).

Để làm như vậy, bạn có thể sử dụng gói [`torch.cuda`](https://pytorch.org/docs/stable/cuda.html).

Thay vì nói về nó, hãy thử nó.

Bạn có thể kiểm tra xem PyTorch có quyền truy cập vào GPU bằng cách sử dụng [`torch.cuda.is_available()`](https://pytorch.org/docs/stable/generated/torch.cuda.is_available.html#torch.cuda.is_available).

In [71]:
# Check for GPU
import torch
torch.cuda.is_available()

True

Nếu lệnh trên xuất ra `True`, PyTorch có thể thấy và sử dụng GPU, nếu nó xuất ra `False`, nó không thể thấy GPU và trong trường hợp đó, bạn sẽ phải quay lại qua các bước cài đặt.

Bây giờ, giả sử bạn muốn thiết lập mã của mình để nó chạy trên CPU *hoặc* GPU nếu có sẵn.

Theo cách đó, nếu bạn hoặc ai đó quyết định chạy mã của bạn, nó sẽ hoạt động bất kể thiết bị tính toán họ đang sử dụng. 

Hãy tạo biến `device` để lưu trữ loại thiết bị nào có sẵn.

In [72]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

Nếu lệnh trên xuất ra `"cuda"` có nghĩa là chúng ta có thể thiết lập tất cả mã PyTorch để sử dụng thiết bị CUDA có sẵn (một GPU) và nếu nó xuất ra `"cpu"`, mã PyTorch của chúng ta sẽ sử dụng CPU.

> **Lưu ý:** Trong PyTorch, thực hành tốt nhất là viết [**mã không phụ thuộc thiết bị**](https://pytorch.org/docs/master/notes/cuda.html#device-agnostic-code). Điều này có nghĩa là mã sẽ chạy trên CPU (luôn có sẵn) hoặc GPU (nếu có sẵn).

Nếu bạn muốn tính toán nhanh hơn, bạn có thể sử dụng GPU nhưng nếu bạn muốn tính toán *nhanh hơn nhiều*, bạn có thể sử dụng nhiều GPUs.

Bạn có thể đếm số GPUs mà PyTorch có quyền truy cập bằng cách sử dụng [`torch.cuda.device_count()`](https://pytorch.org/docs/stable/generated/torch.cuda.device_count.html#torch.cuda.device_count).

In [73]:
# Count number of devices
torch.cuda.device_count()

1

Biết số GPUs mà PyTorch có quyền truy cập là hữu ích trong trường hợp bạn muốn chạy một quy trình cụ thể trên một GPU và quy trình khác trên GPU khác (PyTorch cũng có các tính năng để cho phép bạn chạy một quy trình trên *tất cả* GPUs).

### 2.1 Làm PyTorch chạy trên Apple Silicon

Để chạy PyTorch trên GPUs M1/M2/M3 của Apple, bạn có thể sử dụng module [`torch.backends.mps`](https://pytorch.org/docs/stable/notes/mps.html).

Hãy đảm bảo rằng các phiên bản macOS và Pytorch được cập nhật.

In [4]:
# Check for Apple Silicon GPU
import torch
torch.backends.mps.is_available() # Note this will print false if you're not running on a Mac

True

In [7]:
# Set device type
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'mps'

Như trước, nếu lệnh trên xuất ra `"mps"` có nghĩa là chúng ta có thể thiết lập tất cả mã PyTorch để sử dụng GPU Apple Silicon có sẵn.

In [8]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

### 3. Đưa tensors (và models) lên GPU

Bạn có thể đưa tensors (và models, chúng ta sẽ thấy điều này sau) lên một thiết bị cụ thể bằng cách gọi [`to(device)`](https://pytorch.org/docs/stable/generated/torch.Tensor.to.html) trên chúng. Trong đó `device` là thiết bị đích mà bạn muốn tensor (hoặc model) chuyển đến.

Tại sao làm điều này?

GPUs cung cấp tính toán số học nhanh hơn rất nhiều so với CPUs và nếu GPU không có sẵn, do **mã không phụ thuộc thiết bị** của chúng ta (xem ở trên), nó sẽ chạy trên CPU.

> **Lưu ý:** Đưa tensor lên GPU bằng cách sử dụng `to(device)` (ví dụ: `some_tensor.to(device)`) trả về một bản sao của tensor đó, tức là cùng một tensor sẽ ở trên cả CPU và GPU. Để ghi đè tensors, hãy gán lại chúng:
>
> `some_tensor = some_tensor.to(device)`

Hãy thử tạo một tensor và đưa nó lên GPU (nếu có sẵn).

In [9]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='mps:0')

Nếu bạn có GPU có sẵn, mã trên sẽ xuất ra một cái gì đó như:

```
tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0')
```

Lưu ý tensor thứ hai có `device='cuda:0'`, điều này có nghĩa là nó được lưu trữ trên GPU thứ 0 có sẵn (GPUs được indexed từ 0, nếu hai GPUs có sẵn, chúng sẽ là `'cuda:0'` và `'cuda:1'` tương ứng, lên đến `'cuda:n'`).

### 4. Chuyển tensors trở lại CPU

Nếu chúng ta muốn chuyển tensor trở lại CPU thì sao?

Ví dụ, bạn sẽ muốn làm điều này nếu bạn muốn tương tác với tensors của mình với NumPy (NumPy không tận dụng GPU).

Hãy thử sử dụng phương thức [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) trên `tensor_on_gpu` của chúng ta.

In [75]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

Thay vào đó, để có tensor trở lại CPU và có thể sử dụng được với NumPy, chúng ta có thể sử dụng [`Tensor.cpu()`](https://pytorch.org/docs/stable/generated/torch.Tensor.cpu.html).

Điều này sao chép tensor vào bộ nhớ CPU để nó có thể sử dụng được với CPUs.

In [76]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

Lệnh trên trả về một bản sao của tensor GPU trong bộ nhớ CPU vì vậy tensor gốc vẫn ở trên GPU.

In [77]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Bài tập

Tất cả các bài tập đều tập trung vào việc luyện tập mã ở trên.

Bạn sẽ có thể hoàn thành chúng bằng cách tham khảo từng phần hoặc theo (các) tài nguyên được liên kết.

**Tài nguyên:**

* [Notebook template bài tập cho 00](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb).
* [Notebook lời giải ví dụ cho 00](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/solutions/00_pytorch_fundamentals_exercise_solutions.ipynb) (hãy thử các bài tập *trước khi* xem cái này).

1. Đọc tài liệu - Một phần lớn của deep learning (và học lập trình nói chung) là làm quen với tài liệu của framework cụ thể mà bạn đang sử dụng. Chúng ta sẽ sử dụng tài liệu PyTorch rất nhiều trong suốt phần còn lại của khóa học này. Vì vậy tôi khuyên bạn nên dành 10 phút đọc những điều sau (không sao nếu bạn không hiểu một số thứ ngay bây giờ, trọng tâm chưa phải là hiểu đầy đủ, mà là nhận thức). Xem tài liệu về [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor) và cho [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).
2. Tạo một tensor ngẫu nhiên với shape `(7, 7)`.
3. Thực hiện phép nhân ma trận trên tensor từ 2 với một tensor ngẫu nhiên khác có shape `(1, 7)` (gợi ý: bạn có thể phải transpose tensor thứ hai).
4. Đặt random seed thành `0` và làm lại bài tập 2 & 3.
5. Nói về random seeds, chúng ta đã thấy cách đặt nó với `torch.manual_seed()` nhưng có tương đương GPU không? (gợi ý: bạn sẽ cần xem vào tài liệu cho `torch.cuda` cho cái này). Nếu có, đặt GPU random seed thành `1234`.
6. Tạo hai tensor ngẫu nhiên có shape `(2, 3)` và gửi cả hai lên GPU (bạn sẽ cần quyền truy cập vào GPU cho việc này). Đặt `torch.manual_seed(1234)` khi tạo tensors (điều này không cần phải là GPU random seed).
7. Thực hiện phép nhân ma trận trên các tensors bạn đã tạo ở 6 (một lần nữa, bạn có thể phải điều chỉnh shapes của một trong các tensors).
8. Tìm giá trị maximum và minimum của đầu ra của 7.
9. Tìm các giá trị chỉ mục maximum và minimum của đầu ra của 7.
10. Tạo một tensor ngẫu nhiên với shape `(1, 1, 1, 10)` và sau đó tạo một tensor mới với tất cả các chiều `1` được loại bỏ để còn lại một tensor có shape `(10)`. Đặt seed thành `7` khi bạn tạo nó và in ra tensor đầu tiên và shape của nó cũng như tensor thứ hai và shape của nó.

## Ngoại khóa

* Dành 1 giờ đi qua [tutorial cơ bản PyTorch](https://pytorch.org/tutorials/beginner/basics/intro.html) (tôi khuyên các phần [Quickstart](https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html) và [Tensors](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html)).
* Để tìm hiểu thêm về cách một tensor có thể biểu diễn dữ liệu, xem video này: [What's a tensor?](https://youtu.be/f5liqUk0ZTw)